apiVersion: v1
kind: pod
metadata:
  name: busy-pod
  labels:
    owner: mohan
    env: demo
    region: north
    tier: back
spec:
  containers:
  - image: busybox:latest
    name: busy
    imagePullPolicy: IfNotPresent
    env: 
      - name: os
        value: "ubuntu"
    command:
      - /bin/echo
    args:
      - "$(os), $(debug)"