apiVersion: v1

kind: PersistentVolume

metadata:

name: <pv_name>

spec:

capacity:

storage: 10Gi

accessModes:

– ReadWriteOnce

persistentVolumeReclaimPolicy: Retain

portworxVolume:

volumeID: “<volume_id>”
