apiVersion: storage.k8s.io/v1 
kind: StorageClass #object
metadata: 
  name: local #this is going to be the storage name we can identify the storage class by this name
provisioner: ebs.csi.aws.com   #here we're saying the storage provider was the amazon web services(aws)
parameters:
  type: io1
  iopsPerGB: "10" #I/O operations per second per GiB only for io1
  encrypted: true
allowedTopologies:
- matchLabelExpressions:
  - key: topology.ebs.csi.aws.com/zone 
    values:
    - eu-west-1a #region which we are indicating
