apiVersion: v1
kind: Service
metadata:
  name: service-my-sql-db
spec:
  selector:
    app: myapp
  ports:
  - port: 3000
    protocol: TCP
    targetPort: 443
  type: ExternalName
  externalName: remote.server.url.com