apiVersion: v1
kind: Secret
metadata:
  name: mysecret
type: Opaque
stringData:
  secret.json: |-
	username: bXktYXBw
  password: Mzk1MjgkdmRnN0pi

    {
          username: mynameismohan
	  password: 39af93falfa93

    }


