apiVersion: apps/v1
kind: DaemonSet
metadata:
  name: nginx-daemonset
  namespace: default
  labels:
    app: nginx
spec:
  selector:
    matchLabels:
      app: nginx
  template:
    metadata:
      labels:
        app: nginx
    spec:
      containers:
      - name: nginx
        image: nginx:1.14
        ports:
        - containerPort: 80

#This configuration creates a DaemonSet named nginx-daemonset that will run a container based on the nginx:1.14 Docker image on every node in the cluster. The container will listen on port 80, which is the default port for HTTP traffic.