apiVersion: rbac.authorization.k8s.io/v1
kind: RoleBinding
metadata:
  name: marketing-api
  namespace: marketing
subjects:
- kind: ServiceAccount
  name: marketing-api
roleRef:
  kind: Role
  name: marketing-api
  apiGroup: rbac.authorization.k8s.io
